AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tech Challenge Fase 4 - Sistema de Feedback Completo

Resources:
  # 1. Base de Dados
  FeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Feedback
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  # 2. Tópico de Notificações (SNS)
  AlertaCriticoTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: "humbertofernandes08@hotmail.com"
          Protocol: email

  # 3. Função de Ingestão (API Gateway)
  FeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java21
      CodeUri: target/function.zip
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          QUARKUS_LAMBDA_HANDLER: feedback
      Policies:
        - DynamoDBCrudPolicy: {TableName: Feedback}
      Events:
        AvaliacaoApi:
          Type: Api
          Properties:
            Path: /avaliacao
            Method: post

  # 4. Função de Notificação (Gatilho DynamoDB)
  NotificacaoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java21
      CodeUri: target/function.zip
      Timeout: 30
      Environment:
        Variables:
          QUARKUS_LAMBDA_HANDLER: notificacao
          TOPICO_ALERTA_ARN: !Ref AlertaCriticoTopic
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sns:Publish
              Resource: !Ref AlertaCriticoTopic
      Events:
        FeedbackStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt FeedbackTable.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 1

  # 5. Função de Relatório (Agendada)
  RelatorioFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java21
      CodeUri: target/function.zip
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          QUARKUS_LAMBDA_HANDLER: relatorio
          TOPICO_ALERTA_ARN: !Ref AlertaCriticoTopic
      Policies:
        - DynamoDBReadPolicy: {TableName: Feedback}
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sns:Publish
              Resource: !Ref AlertaCriticoTopic
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 9 ? * MON *) # Toda segunda-feira às 09h UTC

Outputs:
  FeedbackApi:
    Description: "URL para o POST de feedbacks"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/avaliacao/"